rover_serial:
  ros__parameters:
    serial_port: /dev/rover

rover:
  ros__parameters:
    diagnostics_frequency: 0.2
    odometry_frequency: 15.0
    motor_control_p_gain: 0.00005
    motor_control_i_gain: 0.000
    publish_tf: true

joint_state_publisher:
  ros__parameters:
    publish_default_positions: true
    rate: 30